frontend:
	bash components/frontend.sh

mongodb:
	bash components/mongodb.sh

catalogue:
	bash components/catalogue.sh

redis:
	bash components/redis.sh

cart:
	bash components/cart.sh

xyz:
bash scriptName.sh 